### PR TITLE
sync with the messages list from the author's repo

### PR DESCRIPTION
**Pull request by XenHat**

### CODE REVIEW

**Comment by XenHat** [comment]
my knowlege of python is pretty limited, but it might be worth implementing a way to automatically download an updated message file once in a while [from here](https://github.com/ngerakines/commitment/blob/master/commit_messages.txt).

**Comment by janraasch** [comment]
> it might be worth implementing a way to automatically download an updated message file once in a while

You are absolutely right :).

**Comment by janraasch** [comment]
Thanks for the update. Released `v1.0.7` just now. Give it a go :)

**Comment by XenHat** [comment]
Working great! Thanks! :+1:

**Pull request merged**
